pitchout:
  spawn:
    x: 0.5
    y: 0.0
    z: 0.5
    yaw: 0.0
    pitch: 0.0
  game:
    spawn1:
      x: 0.5
      y: 0.0
      z: 0.5
      yaw: 0.0
      pitch: 0.0
    spawn2:
      x: 0.5
      y: 0.0
      z: 0.5
      yaw: 0.0
      pitch: 0.0
    spawn3:
      x: 0.5
      y: 0.0
      z: 0.5
      yaw: 0.0
      pitch: 0.0
    spawn4:
      x: 0.5
      y: 0.0
      z: 0.5
      yaw: 0.0
      pitch: 0.0